language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.2
  - DJANGO=https://github.com/django/django/tarball/stable/1.7.x
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install $DJANGO
  - pip install coverage coveralls

script:
  - coverage run -a setup.py test
  - coverage report

after_success: coveralls
