language: python

python:
  - 3.3

env:
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-djangomaster
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-djangomaster
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-djangomaster
  - TOXENV=pypy2-django16
  - TOXENV=pypy2-django17
  - TOXENV=pypy2-djangomaster

before_install:
  - sudo apt-get update
  - sudo apt-get install python3.4 python3.4-dev

install:
  - pip install tox coveralls

script:
  - tox

after_success: coveralls

notifications:
  hipchat:
    rooms:
      secure: G8gM9YEZqBJxrzvjvycFyFR2Uxu6yuUy3bxQVPpM41tL4Nrr/nNM73U4Nu8RBoBzeontiu29u/fqJ7+J0YY2GuxU9T57v+ARwfK0stLWxzm3dpc3h7SIYTj97w2tXAZljRe945nui3pYIHHVk2vXHcDv+j2Vrkgii2w1D2DvEDs=
