language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - "pypy"

env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="https://github.com/django/django/tarball/stable/1.7.x"
  - DJANGO="https://github.com/django/django/tarball/master"

install:
  - pip install --use-wheel --no-allow-external $DJANGO coverage coveralls

script:
  - which django-admin.py
  - django-admin.py version
  - python -c "import xenforo;print(xenforo.__version__)"
  - coverage run setup.py test
  - coverage report -m

after_success: coveralls

matrix:
  exclude:
    - python: "pypy"
      env: DJANGO="Django>=1.5,<1.6"

notifications:
  hipchat:
    rooms:
      secure: G8gM9YEZqBJxrzvjvycFyFR2Uxu6yuUy3bxQVPpM41tL4Nrr/nNM73U4Nu8RBoBzeontiu29u/fqJ7+J0YY2GuxU9T57v+ARwfK0stLWxzm3dpc3h7SIYTj97w2tXAZljRe945nui3pYIHHVk2vXHcDv+j2Vrkgii2w1D2DvEDs=
